### ISSUE TITLE
[TUTORIAL] Basic Introduction

### ISSUE THREAD

**Issue by billimarie** [billimarie/prosecutor-database#36]
An easy to read, simple, clean instruction manual for those who are not developers by trade.

**Comment by davidth4ever2** [comment]
Nice

On Jul 15, 2018 11:16 AM, "Billimarie Lubiano Robinson" <
notifications@github.com> wrote:

An easy to read, simple, clean instruction manual for those who are not
developers by trade.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/billimarie/prosecutor-database/issues/36>, or mute the
thread

**Comment by davidth4ever2** [comment]
Also,I found that the Washington post has a database as well.

So far there has been almost 600, police shooting ending in death.

**Comment by billimarie** [comment]
@davidth4ever2 Yes, the WP has an effective and clean method for presenting that data: [2018 Police Shootings Database](https://www.washingtonpost.com/graphics/2018/national/police-shootings-2018/).

**Comment by dylmye** [comment]
Hello! I found this issue from up-for-grabs. Are you still asking for help with this as I see you've published [this](https://billimarie.github.io/prosecutor-database/#google)? Thanks :)

**Comment by billimarie** [comment]
Hi @dylmye, just seeing your comment! Feel free to make any improvements to the beginner documentation on the README.md file if you're feeling up to it. Thanks!

**Comment by wnorrad** [comment]
This is a great idea - I’ll do this to hopefully help others! 

Whit Norrad
289-696-3664

**Comment by billimarie** [comment]
@wnorrad That would be wonderful, Whit! Thanks for your perspective and assistance.
